#
# Copyright 2019 justworx
# This file is part of the trix project, distributed under 
# the terms of the GNU Affero General Public License.
#


from .propseq import *


# -------------------------------------------------------------------
#
#
# PROP-LIST
#
#
# -------------------------------------------------------------------

class proplist(propseq):
	"""
	Wrap objects in a proplist to provide a variety of useful features
	for manipulation and display.
	"""
	
	def join(self, glue=DEF_NEWL, **k):
		"""	Use to join those lines of text."""
		x = []
		try:
			for line in self.o:
				x.append(str(line, **k))
		except:
			for line in self.o:
				x.append(str(line))
				
		return glue.join(x)
	
	
	def text(self):
		"""Use to join those lines of text."""
		return self.join(encoding=DEF_ENCODE)
	
	
	def unique(self):
		"""Return a proplist containing the unique set of items."""
		return proplist(list(set(self.o)))
	
	
	def extend(self, additems):
		"""
		Return a proplist containing this list extended by items from the
		list argument `additems`.
		"""
		L = []
		L.extend(self.o)
		L.extend(additems)
		return proplist(L)
	
	
	def compare (self, other_list):
		"""
		Return a propdict object showing a comparison between the
		contents of this object and `other_list`. The dict results are
		interpreted as follows:
		
		 * '+' : objects contained by self.o that are NOT found in other
		 * '=' : objects contained by self.o and other
		 * '-' : objects contained by other, but not self.o 
		
		EXAMPLE:
		#
		# Compare list [1,2,3] against list [2,3,4]
		#
		>>> from trix.util.propx import *
		>>> propx([1,2,3]).compare([2,3,4]).o
		{'-': [4], '+': [1], '=': [2, 3]}
		>>>
		
		In the example, above, the original list [1,2,3] was compared
		to comparison list [2,3,4].
		
		Key values show results as follows:
		 * The minus sign (-) shows items not found in the original list,
		   but found in the comparison list.
		 * The plus sign (+) shows items found in the original list but 
		   not in the comparison list.
		 * The equal sign (=) shows items found in both lists.
		
		The results of comparison are:
		 - 4 was missing from the original list, [1,2,3]
		 + 1 was found in the original list [1,2,3] but not in the 
		   comparison list.
		 = 2 and 3 were found in both lists
		
		"""
		d = {'-':[], '+':[], "=":[]}
		for o in self.o:
			if o in other_list:
				d["="].append(o)   # items in both lists
			else:
				d["+"].append(o)   # items in self.o but not other_list
		
		for x in other_list:
			if not x in self.o:
				d['-'].append(x)
		
		return trix.propx(d)
				
	
	def merge(self, additems):
		"""
		Return a proplist containing a unique set of items from this list
		and the given `additems` list. 
		
		It is exactly: `return self.extend(additems).unique()`
		
		EXAMPLE:
		>>> px = propx([1,2,3]).merge([3,4,5])
		[1, 2, 3, 4, 5]
		>>>
		
		"""
		return propx(self.extend(additems)).unique()
	
	
	def each(self, x, *a, **k):
		"""
		Alter each item given callable `x` and arguments.
		
		Perform callable `x` on each item in the list, applying arguments
		`*a` and keyword arugments `**k`.
		
		Returns a new proplist containing altered items.
		
		EXAMPLE:
		#
		# Decode encoded list items
		#
		>>>
		>>> from trix.util.propx._propall import *
		>>> tp = trix.popen("ps").communicate()
		>>> propx(tp).proplist.each(bytes.decode, encoding='utf8').o
		>>>
		
		"""
		L = []
		for item in self.o:
			L.append( x(item, *a, **k) )
			
		return proplist(L)
	
	
	
	@property
	def propgrid(self):
		"""
		Use only with lists that contain a set of lists of equal length.
		"""
		return propgrid(self.o)
	
	
	@property
	def dbgrid(self):
		return trix.ncreate('data.dbgrid', self.o)



# -------------------------------------------------------------------
#
#
# PROP GRID
#
#
# -------------------------------------------------------------------

class propgrid(proplist):
	"""
	The `propgrid` class separates a header row from the data rows
	that follow. It's intended for data that consists of a list of
	equal-length lists, such as is generated by data.dbgrid.
	
	NOTE: data.dbgrid always prepends the header row to query results.
	      The 'header' kwarg is accepted in case we need to pass a grid
	      (list of lists) that's not prepended with column titles.
	      
	EXAMPLE
	
	
	"""
	
	def __call__(self, *a, **k):
		"""
		The __call__ method overridden to separate the header from the
		data portion of this grid.
		
		When the class is propgrid, all calls to .o are returned from 
		propgrid.o, and all calls to __call__ are returned from here - 
		even when it's superclasses (or even subclasses)  making the
		call - so it's OK to have a different self.__o.
		"""
		try:
			return self.__o
		except:
			#
			# FIRST:
			#  - Get the grid from the propx.__call__ method, where it will
			#    be created from stored constructor args.
			#
			grid = proplist.__call__(self, *a, **k)
			
			#
			# NEXT:
			#  - Intuitively, we *should*, here, be getting the actual grid 
			#    list, but we're not. Instead, we're getting the method that 
			#    was passed to __init__ (along with kwargs) to be executed - 
			#    and a return value set into self.__o - on first call to 
			#    __call__ (and just self.__o returned on subsequent calls).
			#
			
			#
			# SO...
			#  - split the grid header from grid data (if necessary).
			#
			header = self.k.get('header')
			if header:
				self.__o = grid
				self.__h = header
				self.__hh = True
			else:
				self.__o = grid[1:]
				self.__h = grid[0]
				self.__hh = False
			
			return self.__o
	
	
	
	
	
	@property
	def o(self):
		"""
		Override default `self.o` to reflect value custom to this 
		class. That is, the header in grids.
		"""
		try:
			return self.__o
		except:
			self.__call__(*self.a, **self.k)
			return self.__o
	
	@property
	def h(self):
		"""
		Short alias. Returns the value of the header row.
		"""
		try:
			return self.__h
		except:
			self.o
			return self.__h
	
	@property
	def header(self):
		"""Return the value of the header row."""
		return self.h
	
	@property
	def hh(self):
		"""
		Short alias for `self.has_header` - True if a header row exists.
		"""
		try:
			return self.__hh
		except:
			self.o
			return self.__hh
	
	@property
	def has_header(self):
		"""
		Indicates True or False - whether this grid has a header row.
		"""
		return self.hh
	
	
			
	@property
	def gen(self):
		"""
		Generates the header row (if it exists) and all data rows.
		"""
		
		try:
			yield(self.__h)
		except AttributeError:
			#
			# Calling self.o will generate the table if it has not already
			# been created.
			#
			self.o
			yield(self.__h)
		
		for r in self.o:
			yield(r)
	
	
	
	def grid(self, *a, **k):
		"""
		Display this data formatted as a grid.
		
		Overrides `proplist.grid` to expose the header, which propgrid
		separates from the data for easier data-manipulation.
		
		"""
		
		k['f'] = 'Grid'
		trix.display(list(self.gen), *a, **k)
	
	
	
	#
	# DB-GRID
	#
	def dbgrid(self, tableName, **k):
		"""
		Returns a `DBGrid` object containing this object's data in a table
		named by the string `tableName` argument.
		
		The value of any keyword arguments given must be a grid - a list
		of lists containing an equal number of values, with a column name
		list prepended as item zero. An additional table (named for the
		keyword) will be created in the resulting `DBGrid` object.
		
		#
		# NOTE: Database Tables are Always Grids!
		#
		This method will fail if `self.o` (or any suplimentary tables
		defined by the passage of keyword arguments) is not a list
		of lists each containing an equal number of items.
		
		EXAMPLE:
		import trix
		lgrid = trix.path("~/trix").list.propgrid.dbgrid('lgrid')
		return lgrid('select * from lgrid order by mtime desc')
		
		"""
		g = trix.ncreate('data.dbgrid.DBGrid', **k)
		g.add(tableName, self.o, self.h)
		return g


